version: '3.2'
services:
  postgres:
    hostname: postgres
    image: pennsieve/postgres:9.6.5
    environment:
      POSTGRES_PASSWORD: password
      PGPASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /opt/pgdata
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -t postgres -c \"\\d+ pennsieve.users\""]
      # Warning: Do not change this interval! Anything larger will slow down API tests.
      interval: 1s
      timeout: 1s
      retries: 10
    user: postgres

  migrations:
    image: pennsieve/migrations:latest
    environment:
      PENNSIEVE_POSTGRES_HOST: postgres
      PENNSIEVE_POSTGRES_PORT: 5432
      PENNSIEVE_POSTGRES_USER: postgres
      PENNSIEVE_POSTGRES_PASSWORD: password
      PENNSIEVE_POSTGRES_USE_SSL: "false"
    # Override Cloudwrap entrypoint to use explicit environment variables
    entrypoint: ["java", "-jar", "/app/migrations.jar"]

  timeseries-migrations:
    command: |
      alembic
      upgrade
      head
    environment:
      - PENNSIEVE_POSTGRES_HOST=postgres
    hostname: alembic
    image: pennsieve/timeseries-migrations:0782992177f4
    links:
      - postgres:postgres
